### ISSUE TITLE
Baza in .gitignore

### ISSUE THREAD

**Issue by jaanos** [rastko07/webshop#1]
Vidim, da se je na repozitoriju znašlo nekaj datotek z bazami. Te ne sodijo na repozitorij, saj gre za binarne datoteke, ki se pogosto spreminjajo, in git ne zna najbolje delati s takimi datotekami - namesto tega vajin program sam ustvari bazo, če ta še ne obstaja. Za baze uporabljata končnico `.sdb` - svetujem, da morda raje uporabita kar `.db`. Lahko pa v `.gitignore` dodasta še vrstico `*.sdb`; obstoječe datoteke `*.sdb` pa v vsakem primeru pobrišita iz repozitorija.

Mimogrede, opažam še, da delata to:

https://github.com/rastko07/webshop/blob/b33bc2ddc4b8a82ece49b0ce5d250fdb458536d9/baza.py#L51-L53

Glavni ključi so sami po sebi edinstveni in ne smejo imeti vrednosti `NULL`, tako da je navajanje lastnosti `NOT NULL` in `UNIQUE` nepotrebno.

**Comment by rastko07** [comment]
Rešeno v 022eaa381245370f62f773f28e8faaa0d6bb7b37.
